version: '3.8'

services:

 bin:
  image: nginx:alpine
  networks:
  - network2

 api:
  build:
   context: .
   dockerfile: Dockerfile-api
  ports:
  - 8000:5000
  volumes:
  - ./:/app
  networks:
  - network1
  - network2

 mysqldb:
  image: mysql
  ports:
  - 3306:3306
  environment:
  - MYSQL_ROOT_PASSWORD=p@ssw0rd1
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql
  networks:
  - network1

volumes:
  mysql:
  mysql_config:

networks:
  network1:
    driver: bridge
  network2:
    driver: bridge